### ISSUE TITLE
Closing UI window breaks the component and cannot reopen.

### ISSUE THREAD

**Issue by DarrelRonald** [mitevpi/gh-web-ui#1]
Petr

If you close the UI window, the component breaks and i cannot find a way to reopen / trigger the UI window to open.

**Comment by mitevpi** [comment]
This should be fixed now. It's not the *perfect* interaction, but solves the problem.

There's now a boolean toggle on the window launcher - if it is set to `false`, closing the window will keep it close. When it is set to `true` again, the window will relaunch. 
![image](https://user-images.githubusercontent.com/25568566/112689566-dced5000-8e50-11eb-85ca-1db577e2c406.png)
